-- ════════════════════════════════════════════════════════════════════════════
-- Diagnostic: which workbook names failed to match live data (read-only)
-- Explains the districts 41/57 and branches 271/290 gaps from 0016.
-- Run each query in the Supabase SQL editor.
-- ════════════════════════════════════════════════════════════════════════════

-- Q1: Workbook ACCOUNT names with no matching row in accounts.
-- Every (account, district) pair listed here is an INSERT that no-op'd.
WITH expected(account_name, district_name) AS (VALUES
  ('4 Horn Trench & Shoring', 'Direct'),
  ('Allen Trench Safety Corporation', 'Direct'),
  ('BADGER', 'BADGER — Central'),
  ('BADGER', 'BADGER — West'),
  ('BOA Rentals LLC', 'Direct'),
  ('Baupower Group', 'Direct'),
  ('Canhelco', 'Direct'),
  ('Carter Machinery Co., Inc.', 'Direct'),
  ('DP Nicoli', 'DP Nicoli — Northwest'),
  ('Equipment Share', 'Equipment Share - Central'),
  ('Guardian Trench Safety', 'Guardian Trench - West'),
  ('Herc Rentals Inc.', 'Herc Rentals Inc. — Central'),
  ('Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Iron Lot', 'Direct'),
  ('J & B Tool, Inc.', 'Direct'),
  ('Legend Hire Pty Ltd', 'Direct'),
  ('Lite Industries Pty Ltd', 'Direct'),
  ('Max Renaud', 'Direct'),
  ('National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety UK Limited', 'National Trench Safety — Europe'),
  ('Pro Shoring Equipment', 'Direct'),
  ('SOCAL SHIELD', 'Direct'),
  ('ShorQuip Supply, Inc.', 'Direct'),
  ('Southeastern Trench Safety', 'Southeastern Trench Safety — Central'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment ', 'Sunstate Equipment — East'),
  ('Sunstate Equipment ', 'Sunstate Equipment — West'),
  ('TRENCH-ADE, Inc', 'TRENCH-ADE, Inc — Corporate'),
  ('Trench Shoring Company', 'Trench Shoring Company — West'),
  ('U.S. Shoring & Equipment Co.', 'US Shoring - Corporate'),
  ('Underground Products of Texas', 'Direct'),
  ('United Rentals', 'United Rentals — Gulf'),
  ('United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals', 'United Rentals — Midwest'),
  ('United Rentals', 'United Rentals — Mountain'),
  ('United Rentals', 'United Rentals — NorCal'),
  ('United Rentals', 'United Rentals — Northeast'),
  ('United Rentals', 'United Rentals — Northeast Canada'),
  ('United Rentals', 'United Rentals — Southeast'),
  ('United Rentals', 'United Rentals — Southwest'),
  ('United Rentals', 'United Rentals — Western Canada'),
  ('United Rentals of Canada, Inc.', 'United Rentals — Northeast Canada'),
  ('United Rentals of Canada, Inc.', 'United Rentals — Western Canada'),
  ('United Rentals of Canada, Inc. Brantford', 'United Rentals — Northeast Canada'),
  ('Valley Shoring and Safety', 'Direct'),
  ('Vandalia Rental', 'Direct'),
  ('Zip U There, Inc.', 'Direct')
)
SELECT e.account_name AS workbook_account, e.district_name AS district_that_was_skipped
FROM expected e
LEFT JOIN accounts a ON lower(a.name) = lower(e.account_name)
WHERE a.id IS NULL
ORDER BY 1, 2;

-- Q2: Near-miss suggestions for the unmatched accounts (fuzzy contains-match).
WITH expected(account_name, district_name) AS (VALUES
  ('4 Horn Trench & Shoring', 'Direct'),
  ('Allen Trench Safety Corporation', 'Direct'),
  ('BADGER', 'BADGER — Central'),
  ('BADGER', 'BADGER — West'),
  ('BOA Rentals LLC', 'Direct'),
  ('Baupower Group', 'Direct'),
  ('Canhelco', 'Direct'),
  ('Carter Machinery Co., Inc.', 'Direct'),
  ('DP Nicoli', 'DP Nicoli — Northwest'),
  ('Equipment Share', 'Equipment Share - Central'),
  ('Guardian Trench Safety', 'Guardian Trench - West'),
  ('Herc Rentals Inc.', 'Herc Rentals Inc. — Central'),
  ('Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Iron Lot', 'Direct'),
  ('J & B Tool, Inc.', 'Direct'),
  ('Legend Hire Pty Ltd', 'Direct'),
  ('Lite Industries Pty Ltd', 'Direct'),
  ('Max Renaud', 'Direct'),
  ('National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety UK Limited', 'National Trench Safety — Europe'),
  ('Pro Shoring Equipment', 'Direct'),
  ('SOCAL SHIELD', 'Direct'),
  ('ShorQuip Supply, Inc.', 'Direct'),
  ('Southeastern Trench Safety', 'Southeastern Trench Safety — Central'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment ', 'Sunstate Equipment — East'),
  ('Sunstate Equipment ', 'Sunstate Equipment — West'),
  ('TRENCH-ADE, Inc', 'TRENCH-ADE, Inc — Corporate'),
  ('Trench Shoring Company', 'Trench Shoring Company — West'),
  ('U.S. Shoring & Equipment Co.', 'US Shoring - Corporate'),
  ('Underground Products of Texas', 'Direct'),
  ('United Rentals', 'United Rentals — Gulf'),
  ('United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals', 'United Rentals — Midwest'),
  ('United Rentals', 'United Rentals — Mountain'),
  ('United Rentals', 'United Rentals — NorCal'),
  ('United Rentals', 'United Rentals — Northeast'),
  ('United Rentals', 'United Rentals — Northeast Canada'),
  ('United Rentals', 'United Rentals — Southeast'),
  ('United Rentals', 'United Rentals — Southwest'),
  ('United Rentals', 'United Rentals — Western Canada'),
  ('United Rentals of Canada, Inc.', 'United Rentals — Northeast Canada'),
  ('United Rentals of Canada, Inc.', 'United Rentals — Western Canada'),
  ('United Rentals of Canada, Inc. Brantford', 'United Rentals — Northeast Canada'),
  ('Valley Shoring and Safety', 'Direct'),
  ('Vandalia Rental', 'Direct'),
  ('Zip U There, Inc.', 'Direct')
),
unmatched AS (
  SELECT DISTINCT e.account_name
  FROM expected e
  LEFT JOIN accounts a ON lower(a.name) = lower(e.account_name)
  WHERE a.id IS NULL
)
SELECT u.account_name AS workbook_account, a.name AS possible_db_match
FROM unmatched u
JOIN accounts a
  ON lower(a.name) LIKE '%' || lower(left(u.account_name, 12)) || '%'
  OR lower(u.account_name) LIKE '%' || lower(left(a.name, 12)) || '%'
ORDER BY 1, 2;

-- Q3: Workbook BRANCH updates that no-op'd, with the reason
-- (account missing, branch missing, or district missing).
WITH expected(branch_name, account_name, district_name) AS (VALUES
  ('4 Horn Trench & Shoring - Pasadena, TX', '4 Horn Trench & Shoring', 'Direct'),
  ('Allen Trench Safety Corporation - Bellevue, MI', 'Allen Trench Safety Corporation', 'Direct'),
  ('BADGER - Austin, TX', 'BADGER', 'BADGER — Central'),
  ('BADGER - Henderson, CO', 'BADGER', 'BADGER — West'),
  ('BOA Rentals LLC - Waterman, IL', 'BOA Rentals LLC', 'Direct'),
  ('Baupower Group', 'Baupower Group', 'Direct'),
  ('Canhelco - Manassas, VA', 'Canhelco', 'Direct'),
  ('Carter Machinery Co., Inc. - District Heights, MD', 'Carter Machinery Co., Inc.', 'Direct'),
  ('Carter Machinery Co., Inc. - Salem, VA', 'Carter Machinery Co., Inc.', 'Direct'),
  ('DP Nicoli - Bay Point, CA', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - Caldwell, ID', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - Lakewood, WA', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - Salt Lake City, UT', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - San Jose, CA', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - Seattle, WA', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - South San Francisco, CA', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - Spokane, WA', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('DP Nicoli - Wilsonville, OR', 'DP Nicoli', 'DP Nicoli — Northwest'),
  ('Equipment Share - La Porte, TX', 'Equipment Share', 'Equipment Share - Central'),
  ('Equipment Share - Sanford, FL', 'Equipment Share', 'Equipment Share - Central'),
  ('Guardian Trench Safety - Phoenix AZ', 'Guardian Trench Safety', 'Guardian Trench - West'),
  ('Herc Rentals Inc.', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Austin, TX', 'Herc Rentals Inc.', 'Herc Rentals Inc. — Central'),
  ('Herc Rentals Inc. - Bakersfield, CA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Baytown, TX', 'Herc Rentals Inc.', 'Herc Rentals Inc. — Central'),
  ('Herc Rentals Inc. - Charlotte, NC', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Denison, TX', 'Herc Rentals Inc.', 'Herc Rentals Inc. — Central'),
  ('Herc Rentals Inc. - East Point, GA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Foothill Ranch, CA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Gilroy, CA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Lebanon, TN', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Millersville, MD', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - New York, NY', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Newcastle, DE', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Paso Robles, CA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Phoenix, AZ', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Portland, OR', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Rancho Cordova, CA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - S. Hackensack, NJ', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Santa Rosa, CA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Shrewsbury, MA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Tacoma, WA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Herc Rentals Inc. - Tampa, FL', 'Herc Rentals Inc.', 'Herc Rentals Inc. — East'),
  ('Herc Rentals Inc. - Union City, CA', 'Herc Rentals Inc.', 'Herc Rentals Inc. — West'),
  ('Iron Lot - Burlington, NC', 'Iron Lot', 'Direct'),
  ('J & B Tool, Inc. - Dallas, GA', 'J & B Tool, Inc.', 'Direct'),
  ('Legend Hire Pty Ltd - Brisbane', 'Legend Hire Pty Ltd', 'Direct'),
  ('Lite Industries Pty Ltd', 'Lite Industries Pty Ltd', 'Direct'),
  ('Max Renaud', 'Max Renaud', 'Direct'),
  ('National Trench Safety - Albuquerque, NM', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Austin, TX', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Baltimore, MD', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Berthoud, CO', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Birmingham, AL', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Boise, ID', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Burlington, NC', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - CO Springs, CO', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Charlotte, NC', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Cleveland, OH', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Conley, GA', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Corpus Christi, TX', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Davie, FL', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Denver, CO', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Des Moines, IA', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Dracut, MA', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Fontana, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Fort Worth, TX', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Fremont, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Fresno, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Gainesville, GA', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Garner, NC', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Gonzales, LA', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Grand JCT, CO', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Irving, TX', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Jacksonville, FL', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Kansas City, KS', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Las Vegas, NV', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Manassas, VA', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Manchester, PA', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Mukilteo, WA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - North Charleston, SC', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - North Houston, TX', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Orlando, FL', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Parsippany, NJ', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Phoenix, AZ', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Pittsburg, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Pittsburg, PA', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Provo, UT', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Redbluff, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Reno, NV', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Roselle, IL', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Sacramento, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Salt Lake, UT', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - San Antonio, TX', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - San Diego, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - San Leandro, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Santa Ana, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - South Houston, TX', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - St. Louis, MO', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Sulphur, LA', 'National Trench Safety', 'National Trench Safety — Central'),
  ('National Trench Safety - Sylmar, CA', 'National Trench Safety', 'National Trench Safety — West'),
  ('National Trench Safety - Tampa, FL', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety - Toano, VA', 'National Trench Safety', 'National Trench Safety — East'),
  ('National Trench Safety UK Limited', 'National Trench Safety UK Limited', 'National Trench Safety — Europe'),
  ('Pro Shoring Equipment', 'Pro Shoring Equipment', 'Direct'),
  ('SOCAL SHIELD - EL CAJON, CA', 'SOCAL SHIELD', 'Direct'),
  ('ShorQuip Supply, Inc. - Conshohocken, PA', 'ShorQuip Supply, Inc.', 'Direct'),
  ('Southeastern Trench Safety - Fortworth, TX', 'Southeastern Trench Safety', 'Southeastern Trench Safety — Central'),
  ('Southeastern Trench Safety - Kyle, TX', 'Southeastern Trench Safety', 'Southeastern Trench Safety — Central'),
  ('Southeastern Trench Safety - New Braunfels, TX', 'Southeastern Trench Safety', 'Southeastern Trench Safety — Central'),
  ('Sunbelt Rentals - Auburn, CA', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - Austin, TX', 'Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals - Belgrade, MT', 'Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals - Bronx, NY', 'Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals - Charlotte, NC', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Conyers, GA', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Corfu, NY', 'Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals - Elgin, IL', 'Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals - Elkridge, MD', 'Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals - Fairfield, OH', 'Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals - Hermitage, TN', 'Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals - Houston, TX', 'Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals - Indianapolis, IN', 'Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals - Irving, TX', 'Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals - Jacksonville, FL', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Lafayette, CO', 'Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals - Memphis, TN', 'Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals - Newcastle, CA', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - Orlando, FL', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Pacific, WA', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - Piscataway, NJ', 'Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals - Pittsburgh, PA', 'Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals - Pompano Beach, FL', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Portland, OR', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - Quinton, VA', 'Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals - Riverside, CA', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - SLC, UT', 'Sunbelt Rentals', 'Sunbelt Rentals — Midwest'),
  ('Sunbelt Rentals - San Antonio, TX', 'Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals - San Jose, CA', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - San Marcos, CA', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - Slidell, LA', 'Sunbelt Rentals', 'Sunbelt Rentals — Gulf South'),
  ('Sunbelt Rentals - Spartanburg, SC', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Sterling, VA', 'Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals - Tampa, FL', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Trainer, PA', 'Sunbelt Rentals', 'Sunbelt Rentals — Northeast'),
  ('Sunbelt Rentals - Tualatin, OR', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunbelt Rentals - Wake Forest, NC', 'Sunbelt Rentals', 'Sunbelt Rentals — Southeast'),
  ('Sunbelt Rentals - Woodinville, WA', 'Sunbelt Rentals', 'Sunbelt Rentals — West'),
  ('Sunstate Equipment  - Gainesville, GA', 'Sunstate Equipment ', 'Sunstate Equipment — East'),
  ('Sunstate Equipment  - Perris, CA', 'Sunstate Equipment ', 'Sunstate Equipment — West'),
  ('Sunstate Equipment  - Portland, OR', 'Sunstate Equipment ', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Auburn, WA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Baldwin Park, CA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Concord, NC', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Conley, GA', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Converse, TX', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - El Cajon, CA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - El Paso, TX', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Garner, NC', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Grand Prairie, TX', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Houston, TX', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Jacksonville, FL', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Kent, WA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Manor, TX', 'Sunstate Equipment', 'Sunstate Equipment — East'),
  ('Sunstate Equipment - Olympia, WA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Pasco, WA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Phoenix, AZ', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Phoenix, AZ-CORP', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Salem, OR', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - San Bernardino, CA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Tucson, AZ', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('Sunstate Equipment - Woodinville, WA', 'Sunstate Equipment', 'Sunstate Equipment — West'),
  ('TRENCH-ADE, Inc - Houston, TX', 'TRENCH-ADE, Inc', 'TRENCH-ADE, Inc — Corporate'),
  ('TRENCH-ADE, Inc - Irving, TX', 'TRENCH-ADE, Inc', 'TRENCH-ADE, Inc — Corporate'),
  ('TRENCH-ADE, Inc - Phoenix, AZ', 'TRENCH-ADE, Inc', 'TRENCH-ADE, Inc — Corporate'),
  ('Trench Shoring Company - Bakersfield, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - Compton, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - Corona, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - Fresno, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - Fullerton, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - Las Vegas, NV', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - Moorpark, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - Sacramento, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - San Diego, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('Trench Shoring Company - San Leandro, CA', 'Trench Shoring Company', 'Trench Shoring Company — West'),
  ('U.S. Shoring & Equipment Co. - TX', 'U.S. Shoring & Equipment Co.', 'US Shoring - Corporate'),
  ('Underground Products of Texas', 'Underground Products of Texas', 'Direct'),
  ('United Rentals', 'United Rentals', 'United Rentals — Gulf'),
  ('United Rentals - AB Canada', 'United Rentals', 'United Rentals — Western Canada'),
  ('United Rentals - Albuquerque, NM', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Arlington, TX', 'United Rentals', 'United Rentals — Gulf'),
  ('United Rentals - Ashland, VA', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Auburn, NH', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - Austin, TX', 'United Rentals', 'United Rentals — Gulf'),
  ('United Rentals - Bakersfield, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Baldwin Park, CA', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Baltimore, MD', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Bohemia, NY', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - Boise, ID', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Charlotte, NC', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Chesapeake, VA', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Chicago, IL', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Colorado Spring, CO', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Columbia, SC', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Columbus, OH', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Concord, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Denver, CO', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Detroit, MI', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Dorval, QC Canada', 'United Rentals', 'United Rentals — Northeast Canada'),
  ('United Rentals - Edmonton (Canada)', 'United Rentals', 'United Rentals — Western Canada'),
  ('United Rentals - Elizabeth, NJ', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - Fairburn, GA', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Fairfield, OH', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Fresno, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Garden City, GA', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Gonzales, LA', 'United Rentals', 'United Rentals — Gulf'),
  ('United Rentals - Greensboro, NC', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Grimes, IA', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Hayward, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Hayward, CA-HUB', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Houston, TX', 'United Rentals', 'United Rentals — Gulf'),
  ('United Rentals - Hyattsville, MD', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Indianapolis, IN', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Irvine, CA', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Jacksonville, FL', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Kansas City, MO', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Kennesaw, GA', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Knoxville, TN', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Langley, BC Canada', 'United Rentals', 'United Rentals — Western Canada'),
  ('United Rentals - Lansing, MI', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Las Vegas, NV', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Lawrenceville, GA', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Longbeach, CA', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Louisville, KY', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Lubbock, TX', 'United Rentals', 'United Rentals — Gulf'),
  ('United Rentals - Manassas, VA', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Marmet, WV', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Memphis, TN', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Mesa, AZ', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Miami, FL', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Nashville, TN', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - North Charleston, SC', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Oklahoma City, OK', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Omaha, NE', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Orlando, FL', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Ottawa Ont (Canada)', 'United Rentals', 'United Rentals — Northeast Canada'),
  ('United Rentals - Pennsauken, NJ', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - Pensacola, FL', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Phoenix, AZ', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Pompano, FL', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Portland, OR', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Quakertown, PA', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - Raleigh, NC', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Reno, NV', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Richfield, OH', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Riverside, CA', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Rochester, NY', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - SLC, UT', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Sacramento, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - San Antonio, TX', 'United Rentals', 'United Rentals — Gulf'),
  ('United Rentals - San Francisco, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - San Jose, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - San Luis Obispo, CA', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Santa Rosa, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Savage, MN', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Seattle, WA', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Shrewsbury, MA', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - Simpsonville, SC', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals - Spokane, WA', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - St. Louis, MO', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Streamwood, IL', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Tacoma, WA', 'United Rentals', 'United Rentals — Mountain'),
  ('United Rentals - Tampa, FL', 'United Rentals', 'United Rentals — Southeast'),
  ('United Rentals - Tucson, AZ', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Tulsa, OK', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - Turlock, CA', 'United Rentals', 'United Rentals — NorCal'),
  ('United Rentals - Ventura, CA', 'United Rentals', 'United Rentals — Southwest'),
  ('United Rentals - Wallingford, CT', 'United Rentals', 'United Rentals — Northeast'),
  ('United Rentals - Waukesha, WI', 'United Rentals', 'United Rentals — Midwest'),
  ('United Rentals - West Mifflin, PA', 'United Rentals', 'United Rentals — Mid Central'),
  ('United Rentals - Wilmington, NC', 'United Rentals', 'United Rentals — Mid Atlantic'),
  ('United Rentals of Canada, Inc. - Bolton', 'United Rentals of Canada, Inc.', 'United Rentals — Northeast Canada'),
  ('United Rentals of Canada, Inc. - Calgary, AB', 'United Rentals of Canada, Inc.', 'United Rentals — Western Canada'),
  ('United Rentals of Canada, Inc. - NANAIMO, BC', 'United Rentals of Canada, Inc.', 'United Rentals — Western Canada'),
  ('United Rentals of Canada, Inc. - Quebec', 'United Rentals of Canada, Inc.', 'United Rentals — Northeast Canada'),
  ('United Rentals of Canada, Inc. - West St. Paul, MB', 'United Rentals of Canada, Inc.', 'United Rentals — Western Canada'),
  ('United Rentals of Canada, Inc. Brantford', 'United Rentals of Canada, Inc. Brantford', 'United Rentals — Northeast Canada'),
  ('Valley Shoring and Safety - Bakersfield, CA', 'Valley Shoring and Safety', 'Direct'),
  ('Vandalia Rental - Vandalia, OH', 'Vandalia Rental', 'Direct'),
  ('Zip U There, Inc.', 'Zip U There, Inc.', 'Direct')
)
SELECT
  e.branch_name  AS workbook_branch,
  e.account_name AS workbook_account,
  e.district_name AS workbook_district,
  CASE
    WHEN a.id IS NULL THEN 'account name not found'
    WHEN b.id IS NULL THEN 'branch name not found'
    WHEN d.id IS NULL THEN 'district not created (see Q1)'
    ELSE 'matched (should have updated)'
  END AS reason
FROM expected e
LEFT JOIN accounts a ON lower(a.name) = lower(e.account_name)
LEFT JOIN branches b ON lower(b.name) = lower(e.branch_name)
LEFT JOIN districts d ON d.account_id = a.id AND lower(d.name) = lower(e.district_name)
WHERE a.id IS NULL OR b.id IS NULL OR d.id IS NULL
ORDER BY reason, 2, 1;

-- Q4: The inverse view — live branches still lacking a district.
SELECT a.name AS account, b.name AS branch
FROM branches b
JOIN accounts a ON b.account_id = a.id
WHERE b.district_id IS NULL
ORDER BY 1, 2;
